#!/usr/bin/env node

const lines = [
  "Unified runtime facade",
  "",
  "  claw-runtime cloud COMMAND",
  "    Preferred in-repo runtime CLI when direnv is enabled.",
  "",
  "Dependency commands",
  "",
  "  npm run deps:show",
  "    Show pinned repo dependency versions and detected local tool versions.",
  "",
  "  npm run deps:check",
  "    Check latest available versions for auto-managed dependency entries without editing versions.json.",
  "",
  "  npm run deps:bump",
  "    Update auto-managed entries in versions.json to their latest available versions.",
  "",
  "  npm run deps:sync",
  "    Render derived dependency files such as config/docker.build.env and the Cloud Function package manifest.",
  "",
  "  npm run deps:lock:function",
  "    Refresh the Cloud Function package-lock.json from the pinned versions.",
  "",
  "Cloud commands",
  "",
  "These commands use operator defaults from env vars or direnv:",
  "  VM_NAME, PROJECT_ID, ZONE, OPENCLAW_SECRET_NAME",
  "",
  "  claw-runtime cloud help",
  "    Print this command list.",
  "",
  "  claw-runtime cloud push-secret",
  "    Upload config/secrets.cloud.json (or CLOUD_SECRET_FILE) to Secret Manager.",
  "",
  "  claw-runtime cloud sync",
  "    Sync the reviewed app tree to the VM without deploying.",
  "",
  "  claw-runtime cloud deploy",
  "    Sync app files, install host prerequisites, render runtime artifacts, and start the cloud gateway.",
  "",
  "  claw-runtime cloud restart",
  "    Re-render runtime artifacts and restart the cloud gateway without rebuilding the image.",
  "",
  "  claw-runtime cloud rebuild",
  "    Sync app files, force a clean no-cache image rebuild, and recreate the cloud gateway.",
  "",
  "  claw-runtime cloud prune",
  "    Prune unused Docker images on the cloud VM as a separate maintenance step.",
  "",
  "  claw-runtime cloud ps",
  "    Show cloud Docker container status on the VM.",
  "",
  "  claw-runtime cloud logs",
  "    Show openclaw-gateway logs from the cloud VM.",
  "",
  "  claw-runtime cloud agent-logs",
  "    Show the latest cloud agent activity stream and runtime log from the gateway container.",
  "",
  "  claw-runtime cloud logs-download",
  "    Download the cloud session log bundle locally using the current direnv cloud settings.",
  "",
  "  claw-runtime cloud shell",
  "    Open an interactive shell inside the cloud gateway container.",
  "",
  "  claw-runtime cloud tunnel",
  "    Open a local tunnel to the remote cloud gateway at http://127.0.0.1:18789/overview.",
  "",
  "  claw-runtime cloud cron apply",
  "    Reconcile repo-managed cloud cron jobs into the gateway without creating duplicates.",
  "",
  "  claw-runtime cloud cron list",
  "    List installed cloud cron jobs.",
  "",
  "  claw-runtime cloud cron run-digest",
  "    Run the morning digest cron job immediately for debugging.",
  "",
  "  claw-runtime cloud test gmail-read",
  "    Run a Gmail read/search test inside the cloud gateway container.",
  "",
  "  claw-runtime cloud test gmail-send",
  "    Send a Gmail test message from the configured Gmail workflow account from the cloud gateway container.",
  "",
  "  claw-runtime cloud test skill SKILL_NAME",
  "    Run a skill-owned cloud test entrypoint through the generic runtime dispatcher.",
  "",
  "Runtime test tiers currently exist only for local Docker:",
  "  claw-runtime local test basic|core|integration",
  "",
  "Optional overrides:",
  "  CLOUD_SECRET_FILE   Alternate cloud secret file path",
  "  CLOUD_CRON_FILE     Alternate cloud cron config path",
  "  TAIL_LINES          Number of log lines for claw-runtime cloud logs",
  "  AGENT_NAME          Agent name for claw-runtime cloud agent-logs (default: main)",
  "  LOG_VIEW            claw-runtime cloud agent-logs view: messages (default), replies, errors, or full",
  "  SHOW_RUNTIME_LOG    Set to 1 to append the raw runtime log tail to claw-runtime cloud agent-logs",
  "  GMAIL_TEST_TO       Recipient for claw-runtime cloud test gmail-send",
  "  GMAIL_TEST_SUBJECT  Subject for claw-runtime cloud test gmail-send",
  "  SKILL_TEST_MESSAGE  Generic message override for claw-runtime cloud test skill",
  "  SKILL_TEST_TIMEOUT_MS  Generic timeout override for claw-runtime cloud test skill",
  "",
  "Note:",
  "  Use config/cron.example.json as the neutral runtime schema example; keep concrete workspace jobs under workspace/config/."
];

console.log(lines.join("\n"));
