#!/usr/bin/env node

const lines = [
  "Dependency commands",
  "",
  "  npm run deps:show",
  "    Show pinned repo dependency versions and detected local tool versions.",
  "",
  "  npm run deps:check",
  "    Check latest available versions for auto-managed dependency entries without editing versions.json.",
  "",
  "  npm run deps:bump",
  "    Update auto-managed entries in versions.json to their latest available versions.",
  "",
  "  npm run deps:sync",
  "    Render derived dependency files such as config/docker.build.env and the Cloud Function package manifest.",
  "",
  "  npm run deps:lock:function",
  "    Refresh the Cloud Function package-lock.json from the pinned versions.",
  "",
  "Cloud commands",
  "",
  "These commands use operator defaults from env vars or direnv:",
  "  VM_NAME, PROJECT_ID, ZONE, OPENCLAW_SECRET_NAME",
  "",
  "  npm run cloud:help",
  "    Print this command list.",
  "",
  "  npm run cloud:push-secret",
  "    Upload config/secrets.cloud.json (or CLOUD_SECRET_FILE) to Secret Manager.",
  "",
  "  npm run cloud:sync",
  "    Sync the reviewed app tree to the VM without deploying.",
  "",
  "  npm run cloud:deploy",
  "    Sync app files, install host prerequisites, render runtime artifacts, and start the cloud gateway.",
  "",
  "  npm run cloud:restart",
  "    Re-render runtime artifacts and restart the cloud gateway without rebuilding the image.",
  "",
  "  npm run cloud:rebuild",
  "    Sync app files, force a clean no-cache image rebuild, and recreate the cloud gateway.",
  "",
  "  npm run cloud:ps",
  "    Show cloud Docker container status on the VM.",
  "",
  "  npm run cloud:logs",
  "    Show openclaw-gateway logs from the cloud VM.",
  "",
  "  npm run cloud:logs:download",
  "    Download the cloud session log bundle locally using the current direnv cloud settings.",
  "",
  "  npm run cloud:shell",
  "    Open an interactive shell inside the cloud gateway container.",
  "",
  "  npm run cloud:tunnel",
  "    Open a local tunnel to the remote cloud gateway at http://127.0.0.1:18789/overview.",
  "",
  "  npm run cloud:cron:apply",
  "    Reconcile repo-managed cloud cron jobs into the gateway without creating duplicates.",
  "",
  "  npm run cloud:cron:list",
  "    List installed cloud cron jobs.",
  "",
  "  npm run cloud:cron:run:digest",
  "    Run the morning digest cron job immediately for debugging.",
  "",
  "  npm run cloud:test:gmail:read",
  "    Run a Gmail read/search test inside the cloud gateway container.",
  "",
  "  npm run cloud:test:gmail:send",
  "    Send a Gmail test message from automation@example.com from the cloud gateway container.",
  "",
  "  npm run cloud:test:digest",
  "    Run the Pip newsletter digest from the cloud gateway container.",
  "",
  "Optional overrides:",
  "  CLOUD_SECRET_FILE   Alternate cloud secret file path",
  "  CLOUD_CRON_FILE     Alternate cloud cron config path",
  "  TAIL_LINES          Number of log lines for cloud:logs",
  "  GMAIL_TEST_TO       Recipient for cloud:test:gmail:send",
  "  GMAIL_TEST_SUBJECT  Subject for cloud:test:gmail:send",
  "  DIGEST_MESSAGE      Custom agent prompt for cloud:test:digest"
];

console.log(lines.join("\n"));
