#!/usr/bin/env node

const lines = [
  "Dependency commands",
  "",
  "  npm run deps:show",
  "    Show pinned repo dependency versions and detected local tool versions.",
  "",
  "  npm run deps:check",
  "    Check latest available versions for auto-managed dependency entries without editing versions.json.",
  "",
  "  npm run deps:bump",
  "    Update auto-managed entries in versions.json to their latest available versions.",
  "",
  "  npm run deps:sync",
  "    Render derived dependency files such as config/docker.build.env and the Cloud Function package manifest.",
  "",
  "  npm run deps:lock:function",
  "    Refresh the Cloud Function package-lock.json from the pinned versions.",
  "",
  "Local Docker commands",
  "",
  "These commands operate on docker/compose.local.yml in the current repo:",
  "",
  "  npm run local:help",
  "    Print this command list.",
  "",
  "  npm run local:prepare",
  "    Render local runtime artifacts, build the image, and seed writable state paths.",
  "",
  "  npm run local:deploy",
  "    Prepare local Docker and start the local gateway.",
  "",
  "  npm run local:restart",
  "    Re-render local runtime artifacts and restart the local gateway without rebuilding the image.",
  "",
  "  npm run local:rebuild",
  "    Re-render local runtime artifacts, force a clean no-cache rebuild, and recreate the local gateway.",
  "",
  "  npm run local:ps",
  "    Show local Docker container status.",
  "",
  "  npm run local:logs",
  "    Show openclaw-gateway logs from local Docker.",
  "",
  "  npm run local:shell",
  "    Open an interactive shell inside the local gateway container.",
  "",
  "  npm run local:cron:apply",
  "    Reconcile repo-managed local cron jobs into the gateway without creating duplicates.",
  "",
  "  npm run local:cron:list",
  "    List installed local cron jobs.",
  "",
  "  npm run local:cron:run:digest",
  "    Run the local digest cron job immediately for debugging.",
  "",
  "  npm run local:test:gmail:read",
  "    Run a Gmail read/search test inside the local gateway container.",
  "",
  "  npm run local:test:gmail:send",
  "    Send a Gmail test message from automation@example.com from the local gateway container.",
  "",
  "  npm run local:test:digest",
  "    Run the Pip newsletter digest from the local gateway container.",
  "",
  "Optional overrides:",
  "  LOCAL_CRON_FILE     Alternate local cron config path",
  "  TAIL_LINES          Number of log lines for local:logs",
  "  GMAIL_TEST_TO       Recipient for local:test:gmail:send",
  "  GMAIL_TEST_SUBJECT  Subject for local:test:gmail:send",
  "  DIGEST_MESSAGE      Custom agent prompt for local:test:digest",
  "",
  "Note:",
  "  Local cron is disabled by default in config/cron.local.json to avoid duplicate scheduled sends when cloud cron is active."
];

console.log(lines.join("\n"));
