#!/usr/bin/env node

const lines = [
  "Unified runtime facade",
  "",
  "  agent-runtime local COMMAND",
  "    Preferred in-repo runtime CLI when direnv is enabled.",
  "",
  "  npm run rt -- local COMMAND",
  "    Fallback environment-parameterized runtime facade for local Docker commands.",
  "",
  "Dependency commands",
  "",
  "  npm run deps:show",
  "    Show pinned repo dependency versions and detected local tool versions.",
  "",
  "  npm run deps:check",
  "    Check latest available versions for auto-managed dependency entries without editing versions.json.",
  "",
  "  npm run deps:bump",
  "    Update auto-managed entries in versions.json to their latest available versions.",
  "",
  "  npm run deps:sync",
  "    Render derived dependency files such as config/docker.build.env and the Cloud Function package manifest.",
  "",
  "  npm run deps:lock:function",
  "    Refresh the Cloud Function package-lock.json from the pinned versions.",
  "",
  "Local Docker commands",
  "",
  "These commands operate on docker/compose.local.yml in the current repo:",
  "",
  "  npm run local:help",
  "    Print this command list.",
  "",
  "  npm run local:prepare",
  "    Render local runtime artifacts, build the image, and seed writable state paths.",
  "",
  "  npm run local:deploy",
  "    Prepare local Docker and start the local gateway.",
  "",
  "  npm run local:restart",
  "    Re-render local runtime artifacts and restart the local gateway without rebuilding the image.",
  "",
  "  npm run local:rebuild",
  "    Re-render local runtime artifacts, force a clean no-cache rebuild, recreate the local gateway, and prune stale Docker images.",
  "",
  "  npm run local:ps",
  "    Show local Docker container status.",
  "",
  "  npm run local:logs",
  "    Show openclaw-gateway logs from local Docker.",
  "",
  "  npm run local:agent:logs",
  "    Show the latest local agent activity stream and runtime log from the gateway container.",
  "",
  "  npm run local:shell",
  "    Open an interactive shell inside the local gateway container.",
  "",
  "  npm run local:cron:apply",
  "    Reconcile repo-managed local cron jobs into the gateway without creating duplicates.",
  "",
  "  npm run local:cron:list",
  "    List installed local cron jobs.",
  "",
  "  npm run local:cron:run:digest",
  "    Run the local digest cron job immediately for debugging.",
  "",
  "  npm run local:test:gmail:read",
  "    Run a Gmail read/search test inside the local gateway container.",
  "",
  "  npm run local:test:gmail:send",
  "    Send a Gmail test message from pip@meador.me from the local gateway container.",
  "",
  "  npm run local:test:digest",
  "    Run the Pip newsletter digest from the local gateway container.",
  "",
  "  agent-runtime local test basic",
  "    Run the basic local runtime validation tier.",
  "",
  "  agent-runtime local test core",
  "    Run the core local runtime validation tier.",
  "",
  "  agent-runtime local test integration",
  "    Run the integration-oriented local runtime validation tier.",
  "",
  "  agent-runtime local test skill SKILL_NAME",
  "    Run a skill-owned local test entrypoint through the generic runtime dispatcher.",
  "",
  "Optional overrides:",
  "  LOCAL_CRON_FILE     Alternate local cron config path",
  "  TAIL_LINES          Number of log lines for local:logs",
  "  AGENT_NAME          Agent name for local:agent:logs (default: main)",
  "  LOG_VIEW            local:agent:logs view: messages (default), replies, errors, or full",
  "  SHOW_RUNTIME_LOG    Set to 1 to append the raw runtime log tail to local:agent:logs",
  "  GMAIL_TEST_TO       Recipient for local:test:gmail:send",
  "  GMAIL_TEST_SUBJECT  Subject for local:test:gmail:send",
  "  SKILL_TEST_MESSAGE  Generic message override for local:test:skill",
  "  SKILL_TEST_TIMEOUT_MS  Generic timeout override for local:test:skill",
  "  DIGEST_MESSAGE      Custom agent prompt for local:test:digest",
  "  DIGEST_TEST_TIMEOUT_MS  Timeout override for local:test:skill pip-newsletter-digest",
  "  RUNTIME_TEST_SKIP_DEPLOY  Set to 1 to skip the deploy step in local runtime tests",
  "",
  "Note:",
  "  Local cron is disabled by default in config/cron.local.json to avoid duplicate scheduled sends when cloud cron is active."
];

console.log(lines.join("\n"));
